dist: bionic
language: go
go:
  - 1.x
env:
  global:
    - LANG=C
    - LC_ALL=C
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
    - pwnagotchi-*.zip
    - pwnagotchi-*.sha256
  on:
    tags: true
    repo: rdp-studio/pwnagotchi
branches:
  only:
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+[A-Za-z0-9]*$/"
cache:
  apt: true
before_script:
  - travis_wait 60 sudo apt-get -y update || true
  - travis_wait 60 sudo apt-get -y install qemu-system-arm qemu-user-static binfmt-support bmap-tools kpartx
  - travis_wait 60 sudo update-binfmts --display
script:
  - travis_wait 60 sudo make clean
  - travis_wait 60 sudo -E env "PATH=$PATH" make install
  - travis_wait 60 sudo make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=$TRAVIS_TAG
